const btn = 'btn btn-ghost btn-sm hover:bg-neutral-700'

export const styles = {
    body:      'flex flex-col h-screen',
    cnt:       'flex flex-1 overflow-hidden',
    tb:        'bg-base-300 p-4 border-b border-base-content/30 flex items-center',
    left:      'bg-black-400 overflow-auto',
    right:     'bg-base-300 flex-1 overflow-auto',
    grip:      'divider mx-0 divider-horizontal cursor-col-resize',
    iconGrip:  'fa-solid fa-grip-vertical fa-lg text-base-content/50',
    icon:      'fa-solid fa-mg',
    micBtn:    'btn btn-circle btn-lg relative bg-neutral-700 border-b',
    micIcon:   'fa-solid fa-microphone fa-lg',
    micPing:   'absolute inset-0 rounded-full bg-accent animate-ping opacity-75 hidden',
    tiles:     'grid gap-2 p-2',
    tile:         'bg-base-300 p-0 b-1 aspect-square rounded cursor-pointer flex items-center justify-center',
    tileSelected: 'tile-selected',
    tileNum:      'font-bold leading-none',
    slider:    'range range-xs range-primary w-48 ml-8 bg-neutral-600',
    tabs:      'tabs tabs-box bg-primary ml-4',
    tab:       'tab',
    list:      'flex flex-col gap-1 p-2',
    listRow:   'group flex items-center gap-3 px-3 py-2 rounded cursor-pointer hover:bg-neutral-800',
    listRowSelected: 'list-row-selected',
    listNum:   'font-bold w-8 shrink-0',
    listName:      'text-sm flex-1 min-w-0',
    listNameInput: 'text-sm bg-base-content text-base-100 rounded px-2 py-0.5 outline-none border-0 min-w-0 w-full',
    listMark:  'cursor-pointer text-base leading-none select-none',
    listRemoveBtn: `${btn} text-white ml-auto opacity-0 group-hover:opacity-60 hover:!opacity-100 transition-opacity`,
    seqBar:       'sticky top-0 z-10 flex items-center gap-2 px-3 py-2 border-b border-base-content/30 bg-neutral-800 shrink-0',
    seqDropdown:       'dropdown flex-1 border-1 border-base-content/30 rounded',
    seqDropdownBtn:    'btn btn-sm w-full justify-between font-normal',
    seqDropdownMenu:   'dropdown-content menu border-1 border-base-content/20 bg-neutral-800 rounded-box z-10 w-full shadow mt-1 max-h-64 overflow-y-auto flex-nowrap',
    seqDropdownActive: 'active',
    seqNameInput: 'input input-sm flex-1 bg-base-content text-base-100 border-0 outline-none px-2',
    seqBtn:          btn,
    seqIconRename:    'fa-solid fa-pen fa-md',
    seqIconDuplicate: 'fa-solid fa-copy fa-md',
    seqIconDelete:    'fa-solid fa-trash fa-md',
    seqIconChevron:   'fa-solid fa-chevron-down fa-xs',
    listRemoveIcon:   'fa-solid fa-xmark',
    tabActive:        'tab-active',
    player:           'w-full h-full min-h-[300px]',
    techName:         'ml-8 flex-1 text-2xl font-bold uppercase tracking-widest',
}
