export const styles = {
    body:      'flex flex-col h-screen',
    cnt:       'flex flex-1 overflow-hidden',
    tb:        'bg-base-300 p-4 border-b border-base-content/30 flex items-center',
    left:      'bg-base-100 overflow-auto',
    right:     'bg-base-300 flex-1 overflow-auto',
    grip:      'divider mx-0 divider-horizontal cursor-col-resize',
    handle:    'fa-solid fa-grip-vertical text-base-content/50',
    micBtn:    'btn btn-circle relative',
    micIcon:   'fa-solid fa-microphone',
    micPing:   'absolute inset-0 rounded-full bg-accent animate-ping opacity-75 hidden',
    tiles:     'grid gap-2 p-2',
    tile:         'bg-base-300 p-0 b-1 aspect-square rounded cursor-pointer flex items-center justify-center',
    tileSelected: 'tile-selected',
    tileNum:      'font-bold leading-none',
    slider:    'range range-xs range-primary w-48 ml-8',
    tabs:      'tabs tabs-box bg-primary',
    tab:       'tab',
    list:      'flex flex-col gap-1 p-2',
    listRow:   'flex items-center gap-3 px-3 py-2 rounded cursor-pointer hover:bg-base-200',
    listRowSelected: 'list-row-selected',
    listNum:   'font-bold w-8 shrink-0',
    listName:  'text-sm',
    listMark:  'ml-auto cursor-pointer text-base leading-none select-none',
    techName:  'ml-8 flex-1 text-2xl font-bold uppercase tracking-widest',
}
